In [1]:
import matplotlib.pyplot as plt
import numpy as np

import sympy
from sympy import *
from sympy.ntheory import binomial_coefficients_list

import clifford as cf
layout,blades = cf.Cl(3)
from clifford import tools
from clifford.tools import g3
from clifford.g3c import *

In [2]:
blades

{'': 1,
 'e1': (1^e1),
 'e2': (1^e2),
 'e3': (1^e3),
 'e4': (1^e4),
 'e5': (1^e5),
 'e12': (1^e12),
 'e13': (1^e13),
 'e14': (1^e14),
 'e15': (1^e15),
 'e23': (1^e23),
 'e24': (1^e24),
 'e25': (1^e25),
 'e34': (1^e34),
 'e35': (1^e35),
 'e45': (1^e45),
 'e123': (1^e123),
 'e124': (1^e124),
 'e125': (1^e125),
 'e134': (1^e134),
 'e135': (1^e135),
 'e145': (1^e145),
 'e234': (1^e234),
 'e235': (1^e235),
 'e245': (1^e245),
 'e345': (1^e345),
 'e1234': (1^e1234),
 'e1235': (1^e1235),
 'e1245': (1^e1245),
 'e1345': (1^e1345),
 'e2345': (1^e2345),
 'e12345': (1^e12345)}

In [3]:
locals().update(blades)

In [4]:
e1

(1^e1)

In [5]:
from IPython.display import Math



In [6]:
a1 = cf.tools.g3.euc_mv_to_np(e1)
a2 = cf.tools.g3.euc_mv_to_np(e2)
a3 = cf.tools.g3.euc_mv_to_np(e3)
print (a1)
print(a2)
print(a3)

[1 0 0]
[0 1 0]
[0 0 1]


In [7]:
cf.tools.g3.euc_cross_prod(e1,e2)

(1.0^e3)

In [8]:
def cross_prod(a,b):
    return cf.tools.g3.euc_cross_prod(a,b)

In [9]:
cross_prod(e1,e2)

(1.0^e3)

In [10]:
cross_prod(e2,e3)

(1.0^e1)

In [11]:
a=(2*e1+0*e2+4*e3)
b=(0*e1+4*e2+5*e3)
c=(4*e1+5*e2+0*e3)

In [12]:
print(a)

(2^e1) + (4^e3)


In [13]:
cross_prod(a,e3)

-(1.0^e2)

In [15]:
cross_prod(a,b)
b1 = cross(a2, a3) / (a1|cross(a2, a3))

-(0.78072^e1) - (0.48795^e2) + (0.39036^e3)

In [16]:
def reciprocal(a):
    return cross_prod(b,c)/(a|cross_prod(b,c)) 

In [17]:
reciprocal(a)

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [18]:
cross_prod(b,c)

-(0.6985^e1) + (0.5588^e2) - (0.44704^e3)

In [19]:
a|cross_prod(b,c)

-3.18515

In [21]:
cross_prod(b,c)/(a|cross_prod(b,c))

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [22]:
direct_vectors=[a,b,c]

In [23]:
print(direct_vectors)

[(2^e1) + (4^e3), (4^e2) + (5^e3), (4^e1) + (5^e2)]


In [24]:
type(direct_vectors)

list

In [40]:
def reciprocal():
    for i in direct_vectors:
        return cross_prod(i+1,i+2)/(i|cross_prod(i+1,i+2))

In [41]:
reciprocal(direct_vectors(0))

TypeError: 'list' object is not callable