In [1]:
import matplotlib.pyplot as plt
import numpy as np

import sympy
from sympy import *
from sympy.ntheory import binomial_coefficients_list

import clifford as cf
layout,blades = cf.Cl(3)
from clifford import tools
from clifford.tools import g3
from clifford.g3c import *
from clifford import transformations

In [2]:
blades

{'': 1,
 'e1': (1^e1),
 'e2': (1^e2),
 'e3': (1^e3),
 'e4': (1^e4),
 'e5': (1^e5),
 'e12': (1^e12),
 'e13': (1^e13),
 'e14': (1^e14),
 'e15': (1^e15),
 'e23': (1^e23),
 'e24': (1^e24),
 'e25': (1^e25),
 'e34': (1^e34),
 'e35': (1^e35),
 'e45': (1^e45),
 'e123': (1^e123),
 'e124': (1^e124),
 'e125': (1^e125),
 'e134': (1^e134),
 'e135': (1^e135),
 'e145': (1^e145),
 'e234': (1^e234),
 'e235': (1^e235),
 'e245': (1^e245),
 'e345': (1^e345),
 'e1234': (1^e1234),
 'e1235': (1^e1235),
 'e1245': (1^e1245),
 'e1345': (1^e1345),
 'e2345': (1^e2345),
 'e12345': (1^e12345)}

In [3]:
locals().update(blades)

In [4]:
e1

(1^e1)

In [5]:
from IPython.display import Math



In [6]:
a1 = cf.tools.g3.euc_mv_to_np(e1)
a2 = cf.tools.g3.euc_mv_to_np(e2)
a3 = cf.tools.g3.euc_mv_to_np(e3)
print (a1)
print(a2)
print(a3)

[1 0 0]
[0 1 0]
[0 0 1]


In [7]:
cf.tools.g3.euc_cross_prod(e1,e2)

(1.0^e3)

In [8]:
def cross_prod(a,b):
    return cf.tools.g3.euc_cross_prod(a,b)

In [9]:
cross_prod(e1,e2)

(1.0^e3)

In [10]:
cross_prod(e2,e3)

(1.0^e1)

In [11]:
a=(2*e1+0*e2+4*e3)

b=(0*e1+4*e2+5*e3)

c=(4*e1+5*e2+0*e3)

In [12]:
print(a)

(2^e1) + (4^e3)


In [13]:
cross_prod(a,e3)

-(1.0^e2)

In [14]:
cross_prod(a,b)


-(0.78072^e1) - (0.48795^e2) + (0.39036^e3)

In [15]:
def reciprocal_a(x):
    return (cross_prod(b,c))/(a|cross_prod(b,c)) 

def reciprocal_b(y):
    return (cross_prod(c,a))/(b|cross_prod(c,a))

def reciprocal_c(z):
    return (cross_prod(a,b))/(c|cross_prod(a,b))

In [16]:
reciprocal_a(a)

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [17]:
reciprocal_b(b)

-(0.17544^e1) + (0.14035^e2) + (0.08772^e3)

In [18]:
cross_prod(b,c)

-(0.6985^e1) + (0.5588^e2) - (0.44704^e3)

In [19]:
a|cross_prod(b,c)

-3.18515

In [20]:
cross_prod(b,c)/(a|cross_prod(b,c))

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [21]:
direct_vectors=[a,b,c]

In [22]:
print(direct_vectors)

[(2^e1) + (4^e3), (4^e2) + (5^e3), (4^e1) + (5^e2)]


In [23]:
type(direct_vectors)

list

In [24]:
lattice_vectors = {}

In [25]:
type(lattice_vectors)

dict

In [26]:
print(direct_vectors.index(a))

0


In [72]:
def reciprocal(x):
    for i in range(len(direct_vectors)-1):
        if i == 0:
            return(cross_prod(direct_vectors[i+1],direct_vectors[i+2]))/(direct_vectors[i]|cross_prod(direct_vectors[i+1],direct_vectors[i+2]))
        elif i == 1: 
            return(cross_prod(direct_vectors[i+1],direct_vectors[i-1]))/(direct_vectors[i]|cross_prod(direct_vectors[i+1],direct_vectors[i-1]))
    

In [28]:
lattice_vectors[str(a)] = str((reciprocal_a(a)))

In [29]:
print(lattice_vectors)

{'(2^e1) + (4^e3)': '(0.2193^e1) - (0.17544^e2) + (0.14035^e3)'}


In [30]:
direct_recips = {}

In [31]:
def cryst_recip(x,y,z):
    direct_recips[str(x)] = str(reciprocal_a(x))
    direct_recips[str(y)] = str(reciprocal_b(y))
    direct_recips[str(z)] = str(reciprocal_c(z))
    return direct_recips
   

In [32]:
cryst_recip(a,b,c)

{'(2^e1) + (4^e3)': '(0.2193^e1) - (0.17544^e2) + (0.14035^e3)',
 '(4^e2) + (5^e3)': '-(0.17544^e1) + (0.14035^e2) + (0.08772^e3)',
 '(4^e1) + (5^e2)': '(0.14035^e1) + (0.08772^e2) - (0.07018^e3)'}

In [73]:
reciprocal(a)

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [44]:
direct_vectors.index(b)

1

In [74]:
reciprocal(b)

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [65]:
reciprocal(c)

(0.2193^e1) - (0.17544^e2) + (0.14035^e3)

In [51]:
range(len(direct_vectors)-1)

range(0, 2)